services:
  postgres:
    image: postgres:16-alpine
    container_name: lambaripesca_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lambari
      POSTGRES_PASSWORD: lambari
      POSTGRES_DB: lambaripesca
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
